"""empty message

Revision ID: 6cb8884397da
Revises: None
Create Date: 2015-12-17 17:23:52.785321

"""

# revision identifiers, used by Alembic.
revision = '6cb8884397da'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category')
    ### end Alembic commands ###
