"""empty message

Revision ID: 6f1d6055c55c
Revises: 1037bccd1a88
Create Date: 2016-01-06 12:44:08.852379

"""

# revision identifiers, used by Alembic.
revision = '6f1d6055c55c'
down_revision = '1037bccd1a88'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('description', sa.String(length=500), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'description')
    ### end Alembic commands ###
