"""empty message

Revision ID: ae0fe96601f2
Revises: 6cb8884397da
Create Date: 2015-12-18 14:33:44.707411

"""

# revision identifiers, used by Alembic.
revision = 'ae0fe96601f2'
down_revision = '6cb8884397da'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column(u'category', 'name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(u'category', 'name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.drop_table('item')
    ### end Alembic commands ###
