"""empty message

Revision ID: db9d13de559a
Revises: None
Create Date: 2015-12-17 14:55:37.650653

"""

# revision identifiers, used by Alembic.
revision = 'db9d13de559a'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category')
    ### end Alembic commands ###
